### ISSUE TITLE
Assignment Progress

### ISSUE THREAD

**Issue by dluman** [term-world/hall-of-records-assignment#1]
# `TODO`s

Based on the GatorGrader report for this run, here's a summary of what you've got left to do.

## TODOs

- [ ] No TODO markers left in reflection.md or editorial.md
- [ ] Processor.py contains no TODO markers

## Functions

- [ ] Processor.py implements a function called search_rows with 2 parameters
- [ ] Processor.py implements a function called total_column with 1 parameters
- [ ] Processor.py calls a function called search_rows, passing 2 arguments
- [ ] Processor.py calls a function called total_column, passing 1 argument

## Iteration

- [ ] Processor.py iterates (for loop) over the DATA set enough times

## Conditional logic

- [ ] search_rows uses the correct relational operator (&gt;&#x3D;) to test values

## Dictionaries

- [ ] Accesses a dictionary using a key
- [ ] Finds the length of a dictionary

## Percent complete

Based on the checks achieved, this assignment is `0%` complete.
